# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mudata.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.CharField(choices=[('datasets', 'datasets'), ('locations', 'locations'), ('params', 'params'), ('data', 'data'), ('columns', 'columns')], max_length=200)),
                ('column', models.SlugField()),
                ('tags', mudata.models.TagsField()),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.SlugField(unique=True)),
                ('tags', mudata.models.TagsField()),
            ],
        ),
        migrations.CreateModel(
            name='Datum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('value', models.CharField(blank=True, max_length=200, null=True)),
                ('tags', mudata.models.TagsField()),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mudata.Dataset')),
            ],
            options={
                'verbose_name_plural': 'data',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.SlugField()),
                ('tags', mudata.models.TagsField()),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mudata.Dataset')),
            ],
        ),
        migrations.CreateModel(
            name='Param',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param', models.SlugField()),
                ('tags', mudata.models.TagsField()),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mudata.Dataset')),
            ],
        ),
        migrations.AddField(
            model_name='datum',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mudata.Location'),
        ),
        migrations.AddField(
            model_name='datum',
            name='param',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mudata.Param'),
        ),
        migrations.AddField(
            model_name='column',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mudata.Dataset'),
        ),
        migrations.AlterUniqueTogether(
            name='param',
            unique_together=set([('dataset', 'param')]),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set([('dataset', 'location')]),
        ),
        migrations.AlterUniqueTogether(
            name='datum',
            unique_together=set([('dataset', 'location', 'param', 'x')]),
        ),
        migrations.AlterUniqueTogether(
            name='column',
            unique_together=set([('dataset', 'table', 'column')]),
        ),
    ]
