# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.CharField(choices=[('datasets', 'datasets'), ('locations', 'locations'), ('params', 'params'), ('data', 'data'), ('columns', 'columns')], max_length=200)),
                ('column', models.SlugField()),
                ('tags', models.TextField(default='{}')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.SlugField()),
                ('tags', models.TextField(default='{}')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Datum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=200, null=True)),
                ('tags', models.TextField(default='{}')),
                ('x', models.DateTimeField()),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mudata.Dataset')),
            ],
            options={
                'verbose_name_plural': 'data',
            },
        ),
        migrations.CreateModel(
            name='DatumRaw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=200, null=True)),
                ('tags', models.TextField(default='{}')),
                ('x', models.CharField(max_length=200)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mudata.Dataset')),
            ],
            options={
                'verbose_name_plural': 'data_raw',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.SlugField()),
                ('tags', models.TextField(default='{}')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mudata.Dataset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Param',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param', models.SlugField()),
                ('tags', models.TextField(default='{}')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mudata.Dataset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='datumraw',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mudata.Location'),
        ),
        migrations.AddField(
            model_name='datumraw',
            name='param',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mudata.Param'),
        ),
        migrations.AddField(
            model_name='datum',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mudata.Location'),
        ),
        migrations.AddField(
            model_name='datum',
            name='param',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mudata.Param'),
        ),
        migrations.AddField(
            model_name='column',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mudata.Dataset'),
        ),
    ]
