# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 18:48
from __future__ import unicode_literals

from django.db import migrations
import mudata.models


class Migration(migrations.Migration):

    dependencies = [
        ('mudata', '0002_auto_20170509_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='tags',
            field=mudata.models.TagsField(),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='tags',
            field=mudata.models.TagsField(),
        ),
        migrations.AlterField(
            model_name='datum',
            name='tags',
            field=mudata.models.TagsField(),
        ),
        migrations.AlterField(
            model_name='datumraw',
            name='tags',
            field=mudata.models.TagsField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='tags',
            field=mudata.models.TagsField(),
        ),
        migrations.AlterField(
            model_name='param',
            name='tags',
            field=mudata.models.TagsField(),
        ),
    ]
